apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: system
  name: www-deplopyment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
        - name: www
          image: andreaiossa/www-arm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            -
              secretRef:
                name: www-secret
          resources:
            requests:
              cpu: 200m
              memory: 300M
            limits:
              cpu: 500m
              memory: 600M

---
apiVersion: v1
kind: Service
metadata:
  namespace: system
  name: www-service
spec:
  type: ClusterIP
  ports:
    - port: 3004
      targetPort: 8080
  selector:
    app: www
