apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
        - name: www
          image: alessandroperetti89/www:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000  
          envFrom:
            -
              secretRef:
                name: www-secret
---
apiVersion: v1
kind: Service
metadata:
  name: www-service
spec:
  type: ClusterIP
  ports:
    - port: 81
      targetPort: 3000
  selector:
    app: www
