apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: system
  name: www-deplopyment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
        - name: www
          image: alessandroperetti89/www:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080  
          envFrom:
            -
              secretRef:
                name: www-secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: system
  name: www-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: www
