apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: system
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: alessandroperetti89/api
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            -
              secretRef:
                name: api-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: system
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000
      nodePort: 30036
  type: NodePort  
