apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: system
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000
      nodePort: 30036
  type: Nodeport  