# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: system
  name: imaginer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imaginer
  template:
    metadata:
      labels:
        app: imaginer
    spec:
      containers:
      - name: imaginer-container
        image: andreaiossa/imaginer:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: imaginer-secret
        resources:
          requests:
            cpu: 200m
            memory: 300M
          limits:
            cpu: 500m
            memory: 600M


