# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imaginer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imaginer
  template:
    metadata:
      labels:
        app: imaginer
    spec:
      containers:
      - name: imaginer-container
        image: alessandroperetti89/imaginer # personal docker hub
        #command: ["/bin/bash", "-c", "make start"] # injected from Dockerfile
        envFrom:
          -
            secretRef:
              name: api-secret
        volumeMounts:
        - name: app-volume
          mountPath: /app
      volumes:
      - name: app-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: imaginer-service
spec:
  selector:
    app: imaginer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP


