name: imaginer
channels:
  - conda-forge
dependencies:
  - pillow=10.4.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - colorlog=6.8.2
  - dnspython=2.6.1
  - libcxx=18.1.8
  - libexpat=2.6.3
  - libffi=3.4.2
  - libsqlite=3.46.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.2
  - pika=1.3.1
  - pip=24.2
  - pymongo=4.9.1
  - python=3.12.5
  - python_abi=3.12
  - readline=8.2
  - setuptools=74.1.2
  - sniffio=1.3.1
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.2.6
